-- Foundation Studio · Snowflake execution SQL
-- foundation:stage 2
CREATE OR REPLACE TABLE OGFS_DEMO.SILVER.governed_astm_ilsac_test_method_reference AS
SELECT column1::VARCHAR source_method_name, column2::VARCHAR governed_standard_reference, column3::VARCHAR standard_body, column4::VARCHAR method_title, column5::VARCHAR applies_to_business_line, column6::VARCHAR quantity_type
FROM VALUES ('Viscosity','ASTM D445','ASTM','Kinematic Viscosity of Transparent and Opaque Liquids','Lubricants','viscosity'),
('Kinematic Viscosity','ASTM D445','ASTM','Kinematic Viscosity of Transparent and Opaque Liquids','Lubricants','viscosity'),
('Kinematic Viscosity @ 100C','ASTM D445','ASTM','Kinematic Viscosity of Transparent and Opaque Liquids','Lubricants','viscosity'),
('KV100','ASTM D445','ASTM','Kinematic Viscosity of Transparent and Opaque Liquids','Lubricants','viscosity'),
('Visc @ 40C','ASTM D445','ASTM','Kinematic Viscosity of Transparent and Opaque Liquids','Lubricants','viscosity'),
('Flash Point','ASTM D93','ASTM','Flash Point by Pensky-Martens Closed Cup','Fuels','temperature'),
('Flash Pt','ASTM D93','ASTM','Flash Point by Pensky-Martens Closed Cup','Fuels','temperature'),
('Flash Point PMCC','ASTM D93','ASTM','Flash Point by Pensky-Martens Closed Cup','Fuels','temperature'),
('Flash Point COC','ASTM D92','ASTM','Flash Point by Cleveland Open Cup','Lubricants','temperature'),
('Flash Point Open Cup','ASTM D92','ASTM','Flash Point by Cleveland Open Cup','Lubricants','temperature'),
('Pour Point','ASTM D97','ASTM','Pour Point of Petroleum Products','Lubricants','temperature'),
('Acid Number','ASTM D664','ASTM','Acid Number by Potentiometric Titration','Lubricants','concentration'),
('Total Acid Number','ASTM D664','ASTM','Acid Number by Potentiometric Titration','Lubricants','concentration'),
('TAN','ASTM D664','ASTM','Acid Number by Potentiometric Titration','Lubricants','concentration'),
('Base Number','ASTM D4739','ASTM','Base Number by Potentiometric Hydrochloric Acid Titration','Lubricants','concentration'),
('TBN','ASTM D4739','ASTM','Base Number by Potentiometric Hydrochloric Acid Titration','Lubricants','concentration'),
('Sulfur','ASTM D2622','ASTM','Sulfur by Wavelength Dispersive XRF','Fuels','sulfur_trace'),
('Sulphur Content','ASTM D2622','ASTM','Sulfur by Wavelength Dispersive XRF','Fuels','sulfur_trace'),
('Sulfur XRF','ASTM D4294','ASTM','Sulfur by Energy Dispersive XRF','Fuels','sulfur_trace'),
('Sulfur EDXRF','ASTM D4294','ASTM','Sulfur by Energy Dispersive XRF','Fuels','sulfur_trace'),
('Density','ASTM D4052','ASTM','Density, Relative Density, and API Gravity by Digital Density Meter','Fuels','density'),
('API Gravity','ASTM D4052','ASTM','Density, Relative Density, and API Gravity by Digital Density Meter','Fuels','specific_gravity'),
('Water Content','ASTM D6304','ASTM','Water by Coulometric Karl Fischer Titration','Cross-business','concentration'),
('Karl Fischer Water','ASTM D6304','ASTM','Water by Coulometric Karl Fischer Titration','Cross-business','concentration'),
('Ash','ASTM D482','ASTM','Ash from Petroleum Products','Cross-business','concentration'),
('Viscosity Index','ASTM D2270','ASTM','Calculating Viscosity Index from Kinematic Viscosity','Lubricants','viscosity'),
('VI','ASTM D2270','ASTM','Calculating Viscosity Index from Kinematic Viscosity','Lubricants','viscosity'),
('Cold Crank','ASTM D5293','ASTM','Apparent Viscosity by Cold-Cranking Simulator','Lubricants','viscosity'),
('CCS','ASTM D5293','ASTM','Apparent Viscosity by Cold-Cranking Simulator','Lubricants','viscosity'),
('Wear Metals','ASTM D5185','ASTM','Multielement Determination by ICP-AES','Lubricants','sulfur_trace'),
('ICP Metals','ASTM D5185','ASTM','Multielement Determination by ICP-AES','Lubricants','sulfur_trace'),
('Cloud Point','ASTM D2500','ASTM','Cloud Point of Petroleum Products','Fuels','temperature'),
('Color','ASTM D1500','ASTM','ASTM Color of Petroleum Products','Cross-business',NULL),
('Oxidation Stability','ASTM D2274','ASTM','Oxidation Stability of Distillate Fuel Oil','Fuels',NULL),
('Aniline Point','ASTM D611','ASTM','Aniline Point and Mixed Aniline Point','Fuels','temperature'),
('Bromine Number','ASTM D1159','ASTM','Bromine Numbers by Electrometric Titration','Chemicals',NULL),
('Boiling Range Distribution','ASTM D2887','ASTM','Boiling Range Distribution by Gas Chromatography','Fuels',NULL),
('SimDis','ASTM D2887','ASTM','Boiling Range Distribution by Gas Chromatography','Fuels',NULL),
('Cetane Index','ASTM D976','ASTM','Calculated Cetane Index of Distillate Fuels','Fuels',NULL),
('Sequence VIII','ASTM D6709','ASTM','Sequence VIII Engine Test','Lubricants',NULL),
('Sequence IVA','ASTM D6891','ASTM','Sequence IVA Engine Test','Lubricants',NULL),
('Sequence IIIF','ASTM D6984','ASTM','Sequence IIIF Engine Test','Lubricants',NULL),
('Deposit Sequence','ASTM D6593','ASTM','Sequence VG Engine Test for Deposit Formation','Lubricants',NULL),
('ROBO Oxidation','ASTM D7528','ASTM','ROBO Apparatus Oxidation Test','Lubricants',NULL),
('PDSC Oxidation','ASTM D6186','ASTM','Oxidation Induction Time by PDSC','Lubricants',NULL),
('Injector Fouling','ASTM D6421','ASTM','Electronic Port Fuel Injector Fouling','Fuels',NULL),
('Water Reaction Aviation Fuel','ASTM D1094','ASTM','Water Reaction of Aviation Fuels','Fuels',NULL),
('ILSAC GF-6','ILSAC GF-6','ILSAC','Passenger Car Engine Oil Performance Specification','Lubricants',NULL),
('API SP','API SP','API','API Service Category SP','Lubricants',NULL);
