-- Foundation Studio · Snowflake execution SQL
-- foundation:stage 2
CREATE OR REPLACE TABLE OGFS_DEMO.SILVER.unit_registry AS
SELECT column1::VARCHAR canonical_code,column2::VARCHAR display_name,column3::VARCHAR quantity_type,column4::VARCHAR accepted_alias
FROM VALUES ('CST','Centistokes','viscosity','CST'),
('CST','Centistokes','viscosity','cSt'),
('CST','Centistokes','viscosity','centistokes'),
('CST','Centistokes','viscosity','mm2/s'),
('CST','Centistokes','viscosity','mm²/s'),
('SUS','Saybolt Universal Seconds','viscosity','SUS'),
('SUS','Saybolt Universal Seconds','viscosity','SSU'),
('SUS','Saybolt Universal Seconds','viscosity','Saybolt Universal Seconds'),
('DEGC','Degrees Celsius','temperature','DEGC'),
('DEGC','Degrees Celsius','temperature','degC'),
('DEGC','Degrees Celsius','temperature','C'),
('DEGC','Degrees Celsius','temperature','Celsius'),
('DEGC','Degrees Celsius','temperature','deg C'),
('DEGC','Degrees Celsius','temperature','°C'),
('DEGF','Degrees Fahrenheit','temperature','DEGF'),
('DEGF','Degrees Fahrenheit','temperature','degF'),
('DEGF','Degrees Fahrenheit','temperature','F'),
('DEGF','Degrees Fahrenheit','temperature','Fahrenheit'),
('DEGF','Degrees Fahrenheit','temperature','deg F'),
('DEGF','Degrees Fahrenheit','temperature','°F'),
('K','Kelvin','temperature','K'),
('K','Kelvin','temperature','Kelvin'),
('KG_M3','Kilograms per cubic metre','density','KG_M3'),
('KG_M3','Kilograms per cubic metre','density','kg/m3'),
('KG_M3','Kilograms per cubic metre','density','kg/m³'),
('KG_M3','Kilograms per cubic metre','density','kg m-3'),
('G_CM3','Grams per cubic centimetre','density','G_CM3'),
('G_CM3','Grams per cubic centimetre','density','g/cm3'),
('G_CM3','Grams per cubic centimetre','density','g/cm³'),
('SG','Specific gravity','specific_gravity','SG'),
('SG','Specific gravity','specific_gravity','specific gravity'),
('SG','Specific gravity','specific_gravity','relative density'),
('API','API gravity','specific_gravity','API'),
('API','API gravity','specific_gravity','API gravity'),
('API','API gravity','specific_gravity','deg API'),
('API','API gravity','specific_gravity','°API'),
('KG','Kilogram','mass','KG'),
('KG','Kilogram','mass','kg'),
('KG','Kilogram','mass','kilogram'),
('KG','Kilogram','mass','kilograms'),
('G','Gram','mass','G'),
('G','Gram','mass','g'),
('G','Gram','mass','gram'),
('G','Gram','mass','grams'),
('MG','Milligram','mass','MG'),
('MG','Milligram','mass','mg'),
('MG','Milligram','mass','milligram'),
('MG','Milligram','mass','milligrams'),
('LB','Pound','mass','LB'),
('LB','Pound','mass','lb'),
('LB','Pound','mass','lbs'),
('LB','Pound','mass','pound'),
('LB','Pound','mass','pounds'),
('L','Litre','volume','L'),
('L','Litre','volume','l'),
('L','Litre','volume','litre'),
('L','Litre','volume','liter'),
('L','Litre','volume','litres'),
('L','Litre','volume','liters'),
('ML','Millilitre','volume','ML'),
('ML','Millilitre','volume','mL'),
('ML','Millilitre','volume','ml'),
('ML','Millilitre','volume','millilitre'),
('ML','Millilitre','volume','milliliter'),
('M3','Cubic metre','volume','M3'),
('M3','Cubic metre','volume','m3'),
('M3','Cubic metre','volume','m³'),
('M3','Cubic metre','volume','cubic metre'),
('M3','Cubic metre','volume','cubic meter'),
('US_GAL','US gallon','volume','US_GAL'),
('US_GAL','US gallon','volume','US gal'),
('US_GAL','US gallon','volume','gal US'),
('US_GAL','US gallon','volume','US gallon'),
('BAR','Bar','pressure','BAR'),
('BAR','Bar','pressure','bar'),
('BAR','Bar','pressure','bars'),
('KPA','Kilopascal','pressure','KPA'),
('KPA','Kilopascal','pressure','kPa'),
('KPA','Kilopascal','pressure','kilopascal'),
('KPA','Kilopascal','pressure','kilopascals'),
('PSI','Pounds per square inch','pressure','PSI'),
('PSI','Pounds per square inch','pressure','psi'),
('PSI','Pounds per square inch','pressure','lb/in2'),
('MG_KG','Milligrams per kilogram','concentration','MG_KG'),
('MG_KG','Milligrams per kilogram','concentration','mg/kg'),
('MG_KG','Milligrams per kilogram','concentration','ppm'),
('PERCENT','Percent by mass','concentration','PERCENT'),
('PERCENT','Percent by mass','concentration','%'),
('PERCENT','Percent by mass','concentration','wt%'),
('PERCENT','Percent by mass','concentration','mass %'),
('PPM','Parts per million','sulfur_trace','PPM'),
('PPM','Parts per million','sulfur_trace','ppm'),
('PPM','Parts per million','sulfur_trace','mg/kg'),
('PPM','Parts per million','sulfur_trace','mg kg-1'),
('SULFUR_PERCENT','Sulphur percent by mass','sulfur_trace','SULFUR_PERCENT'),
('SULFUR_PERCENT','Sulphur percent by mass','sulfur_trace','% sulfur'),
('SULFUR_PERCENT','Sulphur percent by mass','sulfur_trace','% sulphur'),
('SULFUR_PERCENT','Sulphur percent by mass','sulfur_trace','wt% sulfur'),
('SULFUR_PERCENT','Sulphur percent by mass','sulfur_trace','wt% sulphur');
